### ISSUE TITLE
When the user fills in the wrong detail in login form, the error message is overlapped making unable to understand.

### ISSUE THREAD

**Issue by manjushree7** [Hostel-Management-HCK/HMS-Frontend#7]
![Picture1](https://github.com/Hostel-Management-HCK/HMS-Frontend/assets/119471795/55ab81c1-90f4-40a2-a81c-b88ed31a576e)
 The error message thrown when error occurs during the process is not clustered properly making hard to understand and deal with it.

**Comment by AngelShahi** [comment]
![image](https://github.com/Hostel-Management-HCK/HMS-Frontend/assets/119550468/35dd1a54-77e1-4db9-ae7e-d84cc2755162)
